### ISSUE TITLE
Search polish

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#109]
Followup to #84 to do some non-MVP-but-still-nice-to-have additions for the search:

* [x] More expansive tests - Via #372 and #375
* [x] Result Pagination - Via #375
* [x] When submitting an empty form on desktop, the page is very bleak. It should show at least some "please add a query message or so". On mobile this problem is not that prominent since the search input form is full-width and large there. - Via #376
* [x] Similar issue when submitting a query with 0 results - Via #376
* [x] Focus the form input on initial access (or empty query) on mobile - Via #376
* [x] Put the button into bulma's loading state after submit - Via #376

**Comment by colszowka** [comment]
Adressed via #372, #375 and #376, closing. Further improvements to search, i.e. relating to result relevance, will take place in separate, future PRs.
